-- ============================================================================
-- JC-APEX MASTER DATABASE SCHEMA
-- Version: 2.1 | Date: 2026-10-07
-- Purpose: Production-ready unified schema for Electrothon 48V telemetry system
-- ============================================================================
-- This master file consolidates all database migrations, schemas, and policies
-- into a single production-ready SQL script.
--
-- Tables:
--   - telemetry_logs: Real-time hardware telemetry (volts, amps, watts, speed, GPS)
--   - commands: Pit-to-driver command history
--   - race_flags: Race control flag state
--
-- Features:
--   - Row Level Security (RLS) with permissive policies for race operations
--   - Supabase Realtime publication enabled on all tables
--   - Optimized indexes for time-series queries
--   - Session metrics calculation function
-- ============================================================================

-- ============================================================================
-- STEP 1: DROP EXISTING TABLES (clean slate for production deployment)
-- ============================================================================
DROP TABLE IF EXISTS public.telemetry_logs CASCADE;
DROP TABLE IF EXISTS public.commands CASCADE;
DROP TABLE IF EXISTS public.race_flags CASCADE;

-- ============================================================================
-- STEP 2: CREATE TELEMETRY_LOGS TABLE (aligned with receiver firmware)
-- ============================================================================
CREATE TABLE public.telemetry_logs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMPTZ DEFAULT NOW() NOT NULL,
    session_id TEXT DEFAULT 'race-session-48v',
    volts NUMERIC(5,2) DEFAULT 0.00,
    amps NUMERIC(5,2) DEFAULT 0.00,
    watts NUMERIC(6,2) DEFAULT 0.00,
    speed_h NUMERIC(4,1) DEFAULT 0.0,
    speed_g NUMERIC(4,1) DEFAULT 0.0,
    rssi INT DEFAULT 0,
    snr NUMERIC(4,1) DEFAULT 0.0
);

-- Create indexes for performance
CREATE INDEX idx_telemetry_logs_session_id ON public.telemetry_logs(session_id);
CREATE INDEX idx_telemetry_logs_created_at ON public.telemetry_logs(created_at DESC);
CREATE INDEX idx_telemetry_logs_session_time ON public.telemetry_logs(session_id, created_at DESC);

-- ============================================================================
-- STEP 3: CREATE COMMANDS TABLE (pit-to-driver command history)
-- ============================================================================
CREATE TABLE public.commands (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMPTZ DEFAULT NOW() NOT NULL,
    session_id TEXT DEFAULT 'race-session-48v',
    command_name TEXT NOT NULL,
    status TEXT DEFAULT 'PENDING',
    acknowledged_at TIMESTAMPTZ
);

-- Create indexes
CREATE INDEX idx_commands_session_id ON public.commands(session_id);
CREATE INDEX idx_commands_status ON public.commands(status);
CREATE INDEX idx_commands_created_at ON public.commands(created_at DESC);

-- ============================================================================
-- STEP 4: CREATE RACE_FLAGS TABLE (race control flag state)
-- ============================================================================
CREATE TABLE public.race_flags (
    id INT PRIMARY KEY DEFAULT 1,
    updated_at TIMESTAMPTZ DEFAULT NOW() NOT NULL,
    active_flag TEXT DEFAULT 'GREEN'
);

-- Initialize race flags
INSERT INTO public.race_flags (id, active_flag) VALUES (1, 'GREEN') ON CONFLICT (id) DO NOTHING;

-- ============================================================================
-- STEP 5: ENABLE ROW LEVEL SECURITY (RLS)
-- ============================================================================
ALTER TABLE public.telemetry_logs ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.commands ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.race_flags ENABLE ROW LEVEL SECURITY;

-- ============================================================================
-- STEP 6: CREATE PERMISSIVE RLS POLICIES (eliminate auth blocks for race ops)
-- ============================================================================
-- telemetry_logs: Allow all operations for all users
DROP POLICY IF EXISTS "telemetry_logs_allow_all" ON public.telemetry_logs;
CREATE POLICY "telemetry_logs_allow_all" ON public.telemetry_logs
    FOR ALL
    USING (true)
    WITH CHECK (true);

-- commands: Allow all operations for all users
DROP POLICY IF EXISTS "commands_allow_all" ON public.commands;
CREATE POLICY "commands_allow_all" ON public.commands
    FOR ALL
    USING (true)
    WITH CHECK (true);

-- race_flags: Allow all operations for all users
DROP POLICY IF EXISTS "race_flags_allow_all" ON public.race_flags;
CREATE POLICY "race_flags_allow_all" ON public.race_flags
    FOR ALL
    USING (true)
    WITH CHECK (true);

-- ============================================================================
-- STEP 7: ENABLE REALTIME PUBLICATION
-- ============================================================================
-- Add tables to supabase_realtime publication
DO $$
BEGIN
    -- Add telemetry_logs
    IF NOT EXISTS (
        SELECT 1 FROM pg_publication_tables
        WHERE pubname = 'supabase_realtime'
        AND schemaname = 'public'
        AND tablename = 'telemetry_logs'
    ) THEN
        ALTER PUBLICATION supabase_realtime ADD TABLE public.telemetry_logs;
    END IF;

    -- Add commands
    IF NOT EXISTS (
        SELECT 1 FROM pg_publication_tables
        WHERE pubname = 'supabase_realtime'
        AND schemaname = 'public'
        AND tablename = 'commands'
    ) THEN
        ALTER PUBLICATION supabase_realtime ADD TABLE public.commands;
    END IF;

    -- Add race_flags
    IF NOT EXISTS (
        SELECT 1 FROM pg_publication_tables
        WHERE pubname = 'supabase_realtime'
        AND schemaname = 'public'
        AND tablename = 'race_flags'
    ) THEN
        ALTER PUBLICATION supabase_realtime ADD TABLE public.race_flags;
    END IF;
END $$;

-- ============================================================================
-- STEP 8: VERIFY PUBLICATION
-- ============================================================================
SELECT * FROM pg_publication_tables WHERE pubname = 'supabase_realtime';

-- ============================================================================
-- STEP 9: CREATE HELPER FUNCTION FOR SESSION METRICS
-- ============================================================================
CREATE OR REPLACE FUNCTION calculate_session_metrics(session_id_param TEXT)
RETURNS TABLE (
  session_id TEXT,
  total_records BIGINT,
  peak_current NUMERIC,
  avg_current NUMERIC,
  min_current NUMERIC,
  duration_seconds NUMERIC,
  avg_rssi NUMERIC,
  avg_snr NUMERIC
) AS $$
BEGIN
  RETURN QUERY
  SELECT
    tl.session_id,
    COUNT(*) as total_records,
    MAX(tl.amps) as peak_current,
    AVG(tl.amps) as avg_current,
    MIN(tl.amps) as min_current,
    EXTRACT(EPOCH FROM (MAX(tl.created_at) - MIN(tl.created_at))) as duration_seconds,
    AVG(tl.rssi) as avg_rssi,
    AVG(tl.snr) as avg_snr
  FROM public.telemetry_logs tl
  WHERE tl.session_id = session_id_param
  GROUP BY tl.session_id;
END;
$$ LANGUAGE plpgsql;

-- ============================================================================
-- MIGRATION COMPLETE
-- ============================================================================
-- Verify schema:
-- \d public.telemetry_logs
-- \d public.commands
-- \d public.race_flags
-- SELECT * FROM pg_publication_tables WHERE pubname = 'supabase_realtime';
-- ============================================================================
